android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-23.0.1
    - android-28

    # Support library
    - extra-android-support
    - extra-android-m2repository
    
   script:
        - chmod +x ./gradlew